spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/employees?serverTimezone=Europe/Berlin
    username: root
    password: password
  data:
    rest:
      base-path: /api
  main:
    allow-bean-definition-overriding: true