spring:
  application:
    name: employees-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/employees?serverTimezone=Europe/Berlin
    username: root
    password: password
  data:
    rest:
      base-path: /api
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: false

server:
  port: 8085

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
  lease:
    duration: 5